# Generated by Django 3.0.7 on 2020-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20200611_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
